### ISSUE TITLE
Bower, Typings, Grunt-cli all fail on creating nativesdk

### ISSUE THREAD

**Issue by mdavis777** [imyller/meta-nodejs-contrib#1]
I am trying to get nodejs, bower, typings, and grunt to install as part of the Krogoth SDK.  Nodejs was easy enough to edit and get working however bower, typings, and grunt all fail.  The do_install appears to work, but there are no files in the image directory.
do_install log shows the following error:

Error: setuid user id does not exist
    at /build/core-toolchain_x86_64/tmp-glibc/sysroots/x86_64-linux/usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:49:16
    at ChildProcess.exithandler (child_process.js:193:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

Been fighting it for a couple days and haven't gotten any head way into why this is happening.  Everything works for target and native builds, but breaks for nativesdk.

**Comment by imyller** [comment]
I'll take a look at this too.

I've personally never needed nativesdk targets so maybe this is a good reason to start 👍

**Comment by mdavis777** [comment]
It appears to be any npm install -g inside the nativesdk framework that fails.

**Comment by mdavis777** [comment]
Disabling that check for node-js also works.  Don't know what issues that may causes elsewhere.  
http://tech.panshin.me/technology/qnap-node-js-installation.html

**Comment by imyller** [comment]
> Nodejs was easy enough to edit and get working

What did you exactly edit/change?

**Comment by imyller** [comment]
I took a quick look at the issue; with following initial findings:

```
| UID: nobody
| GID: 0
```

npm is requesting process UID/GID to be changed to nobody with group ID 0. Uses `uid-number` module for that.

build host sysroot has following `/etc/passwd`:

```
root::0:0:root:/home/root:/bin/sh
```

Obviously no entry for `nobody` which usually has entry like this:

```
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
```

This causes following code to fail:

```
  process.setgid(group)
  process.setuid(user)
```

I see few possible solutions to this situation:

a) Making sure that `nobody` user is created for build host sysroot. Should be possible with Yocto+bitbake+OE core.

b)  Configuring NPM not to request uid/gid fork (Haven't looked if there is an visible/hidden option for that yet) 

c) Patching NPM not to request a uid/gid fork

d) Patching `uid-number` number module (solution offered at various sites, for example the one you linked)

Some of these options are more elegant, others less elegant. I'd like to find solution that does not involve patching npm or it's internal dependencies.

**Comment by imyller** [comment]
Update:

We might be in luck:

https://docs.npmjs.com/misc/config#unsafe-perm

npm indeed has an option, that directly or as a side-effect prevents calling the `uid-number` module and uid/gid forking completely.

Best solution to this could be that `meta-nodejs` `npm` class is configured to automatically run npm with `unsafe-perm` configuration option enabled for `nativesdk` targets.

It's going to take a while to test, but I'll try to do so soon.

**Comment by imyller** [comment]
Update #3:

Tested and it works! 

I'll update `meta-nodejs` layer shortly with new `npm-base` class that has support for running `oe_runnpm` in nativesdk context. 

The fix affects `npm-install` and `npm-install-global` classes too; obviously.

**Comment by mdavis777** [comment]
Good to hear.  I am going to spend some time looking into how to get the nobody user created.  It will fix the issue without having to resort to changing the functionality of node-js.

**Comment by imyller** [comment]
No need for that @mdavis777 

`meta-nodejs` now includes a permanent patch for the issue without adding `nobody` user to native host sysroot.

Can you test with the updated `meta-nodejs` and report if there are any remaining issues?

**Comment by imyller** [comment]
In my build server this solution seems to be working:

For example: by looking at buildhistory `files-in-package.txt` for `nativesdk-typings` package now includes all typings files.

**Comment by imyller** [comment]
Linking this for reference: 
https://github.com/imyller/meta-nodejs/commit/11bbaa44a22d56fb62cbe7ddb6cae92d69d46fa5

**Comment by mdavis777** [comment]
Yep looks like it fixed that issue.  I also did a test with the nobody user created which works fine as well.  I may push that to oe-core just in case they deprecate unsafe-perm or it breaks something else.

There are still some issues with getting it to build the native-sdk, but I think I can handle those.

Thanks for the help.

**Comment by imyller** [comment]
Thanks 👍 

Please keep me informed if there is something that can be fixed/improved in `meta-nodejs` or `meta-nodejs-contrib` layer.

I'd like to keep these layers as feature complete as possible without users having to use custom forks for trivial issues.

I'm closing this issue as resolved.
